#!/usr/bin/env sh

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix |
  sh -s -- install

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

export NIXPKGS_ALLOW_UNFREE=1
nix --experimental-features 'nix-command flakes' profile install --impure gitlab:fladnix/flad#cli-base
nix --experimental-features 'nix-command flakes' profile install --impure gitlab:fladnix/flad#desktop-base

cd base
stow --dotfiles --target=$HOME *

mkdir -p ~/.local/share/fonts
wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip \
&& cd ~/.local/share/fonts \
&& unzip JetBrainsMono.zip \
&& rm JetBrainsMono.zip \
&& fc-cache -fv
