# Autoload plug.kak
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
        printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

# modules
plug "lePerdu/kakboard" %{
        hook global WinCreate .* %{ kakboard-enable }
}

# LSP
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# rest of config
source "%val{config}/keymapping.kak"
source "%val{config}/text-options.kak"
source "%val{config}/user-modes.kak"

